# Generated by Django 5.2.8 on 2025-11-23 07:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, help_text='TMDb movie ID', unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
                ('vote_average', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('genre_ids', models.JSONField(blank=True, default=list, help_text='List of genre IDs')),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity', '-vote_average'],
                'indexes': [models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'), models.Index(fields=['vote_average'], name='movies_movi_vote_av_ca6eee_idx'), models.Index(fields=['-popularity'], name='movies_movi_popular_3c541f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes about this movie", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='movies.movie')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'movie'], name='movies_favo_user_id_33a055_idx'), models.Index(fields=['-created_at'], name='movies_favo_created_3cd562_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
